In [2]:
import numpy as np
#integer array
np.array([1,4,6,8,10])

array([ 1,  4,  6,  8, 10])

In [6]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
#crear tabla de 3*5
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
np.arange(0, 22, 2)
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 15, 5 )

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [20]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 7))

array([[0.35830145, 0.02877452, 0.73348345, 0.55434378, 0.74401789,
        0.5459675 , 0.08113361],
       [0.16666867, 0.92184565, 0.15478857, 0.14223191, 0.56152908,
        0.83101341, 0.71797596],
       [0.00948562, 0.92004888, 0.22930173, 0.95236906, 0.7504834 ,
        0.24380569, 0.16447411]])

In [22]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.09596197, -0.77665513, -0.53473308],
       [-1.13467109, -1.65354044, -0.5091634 ],
       [-0.50243991,  0.53277172,  0.05386017]])

In [ ]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[9, 6, 2],
       [5, 5, 1],
       [2, 9, 0]])

In [29]:
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [33]:
np.random.seed
x1 = np.random.randint(10, size=6) #array de una dimension
x2 = np.random.randint(10, size=(3, 4)) ##array de 2 dimeniones
x3 = np.random.randint(10, size=(3, 4, 5)) #array de 3 dimensiones
x3

array([[[0, 9, 6, 7, 7],
        [9, 3, 2, 5, 4],
        [4, 5, 6, 9, 1],
        [8, 8, 2, 6, 5]],

       [[0, 2, 5, 6, 6],
        [4, 0, 3, 9, 0],
        [4, 6, 2, 7, 9],
        [8, 3, 8, 7, 3]],

       [[9, 7, 6, 9, 2],
        [4, 9, 3, 4, 2],
        [8, 1, 9, 6, 3],
        [5, 1, 0, 6, 0]]])